//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupItem()
        {
            this.GroupItem_Sub = new HashSet<GroupItem_Sub>();
        }
    
        public int GroupItem_ID { get; set; }
        public string GroupItem_Code { get; set; }
        public string Name { get; set; }
        public string TitleKey { get; set; }
        public string ParentId { get; set; }
        public string ParenName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupItem_Sub> GroupItem_Sub { get; set; }
    }
}
