//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupItem_Sub
    {
        public int GroupItemSub_ID { get; set; }
        public string GroupItemSub_Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupItem_ID { get; set; }
    
        public virtual GroupItem GroupItem { get; set; }
    }
}
