//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Input_Item_MS
    {
        public int Input_Item_MS_ID { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Vendor_ID { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> AmountDebit { get; set; }
        public Nullable<bool> Type { get; set; }
    }
}
