//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Item_DT
    {
        public int Invoice_Item_DT_ID { get; set; }
        public Nullable<int> Invoice_Item_MS_ID { get; set; }
        public Nullable<int> Item_ID { get; set; }
        public string Item_Code { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Item_Count { get; set; }
        public Nullable<decimal> Item_Unit { get; set; }
        public Nullable<decimal> AmountSaleOf { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
