//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice_Item_MS
    {
        public int Invoice_Item_MS_ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Branch_ID { get; set; }
        public Nullable<int> Employee_ID { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> TotalCount { get; set; }
    }
}
