//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int Item_ID { get; set; }
        public string Item_Code { get; set; }
        public string Name { get; set; }
        public Nullable<int> GroupItem_ID { get; set; }
        public Nullable<int> GroupItem_Sub_ID { get; set; }
        public Nullable<decimal> AmountSale { get; set; }
        public Nullable<decimal> AmountOrigin { get; set; }
        public Nullable<int> Blance { get; set; }
        public Nullable<int> Item_Color_ID { get; set; }
        public Nullable<int> Item_Material_ID { get; set; }
        public Nullable<int> Item_Size_ID { get; set; }
        public string Unit { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> AmountShip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
    }
}
