//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BangAn_2017Entities : DbContext
    {
        public BangAn_2017Entities()
            : base("name=BangAn_2017Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GroupItem> GroupItems { get; set; }
        public virtual DbSet<GroupItem_Sub> GroupItem_Sub { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Input_Item_DT> Input_Item_DT { get; set; }
        public virtual DbSet<Input_Item_MS> Input_Item_MS { get; set; }
        public virtual DbSet<Invoice_Item_DT> Invoice_Item_DT { get; set; }
        public virtual DbSet<Invoice_Item_MS> Invoice_Item_MS { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_Color> Item_Color { get; set; }
        public virtual DbSet<Item_Size> Item_Size { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tranfer_Item_DT> Tranfer_Item_DT { get; set; }
        public virtual DbSet<Tranfer_Item_MS> Tranfer_Item_MS { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
        public virtual DbSet<Item_Material> Item_Material { get; set; }
        public virtual DbSet<Item_Image> Item_Image { get; set; }
    }
}
