//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementStore.EntityFramwork.DbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Vendor_ID { get; set; }
        public string Vendor_Code { get; set; }
        public string Name { get; set; }
        public string Company_Name { get; set; }
        public string Tax_Code { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string Region { get; set; }
        public string CommuneWard { get; set; }
        public string Email { get; set; }
        public string Group_Vendor { get; set; }
        public string Note { get; set; }
    }
}
